module.exports = {
  darkMode: "class",
  content: ["./*.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "error-container": "#fe8983",
        "surface-container-high": "#f0eee5",
        "secondary-fixed": "#ffdad6",
        "primary-dim": "#535252",
        "on-tertiary-fixed": "#494a4a",
        "surface-dim": "#e4e3d7",
        "tertiary-fixed": "#f4f3f3",
        "inverse-on-surface": "#9e9d98",
        "surface-variant": "#eae9de",
        "on-secondary-fixed": "#85000d",
        error: "#a64542",
        background: "#fffcf7",
        "on-primary-fixed-variant": "#5c5b5b",
        "tertiary-fixed-dim": "#e6e5e5",
        "on-secondary-container": "#a70515",
        "inverse-primary": "#ffffff",
        "tertiary-dim": "#585858",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#64655d",
        "on-primary-fixed": "#403f3f",
        "outline-variant": "#babab0",
        "on-background": "#373831",
        "surface-tint": "#5f5e5e",
        "on-surface": "#373831",
        "secondary-fixed-dim": "#ffc7c1",
        "surface-container": "#f6f4ec",
        "secondary-container": "#ffdad6",
        secondary: "#c22225",
        "on-error-container": "#752121",
        "surface-container-low": "#fcf9f3",
        "secondary-dim": "#b1111b",
        "on-tertiary-container": "#5b5c5c",
        "surface-container-highest": "#eae9de",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#d6d4d3",
        "primary-fixed": "#e5e2e1",
        surface: "#fffcf7",
        "on-tertiary-fixed-variant": "#666666",
        "on-secondary": "#ffffff",
        tertiary: "#646464",
        outline: "#818178",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#0e0e0c",
        "error-dim": "#4e0309",
        "on-secondary-fixed-variant": "#b5161e",
        "tertiary-container": "#f4f3f3",
        "surface-bright": "#fffcf7",
        primary: "#5f5e5e",
        "on-primary": "#faf7f6",
        "primary-container": "#e5e2e1",
        "on-primary-container": "#525151"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      fontFamily: {
        headline: ["Noto Serif KR", "Noto Serif", "serif"],
        display: ["Noto Serif KR", "Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"]
      }
    }
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")]
};
